name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Execute Deployment Script on VMWare
        shell: cmd
        run: |
          powershell.exe -ExecutionPolicy Bypass -File C:\laragon\www\deploy.ps1
